from src.ingestion.synthetic_stream import generate_dataset
from src.decision.optimizer import generate_decisions


# =========================================================
# Execute Athena Decisions
# =========================================================

def execute_decision(decision):
    """
    Simulate execution of an optimization decision.

    In a real system this would call APIs for platforms
    such as Meta Ads or Google Ads.
    """

    action = decision["action"]

    campaign_id = decision["campaign_id"]

    current_spend = decision["current_spend"]

    recommended_spend = decision["recommended_spend"]

    # -----------------------------------------------------
    # SCALE
    # -----------------------------------------------------

    if action == "SCALE":

        return {
            "campaign_id": campaign_id,
            "action": "SCALE",
            "status": "EXECUTED",
            "previous_budget": current_spend,
            "new_budget": recommended_spend,
            "message": (
                f"Budget increased from "
                f"₹{current_spend:,.2f} to "
                f"₹{recommended_spend:,.2f}"
            ),
        }

    # -----------------------------------------------------
    # REDUCE
    # -----------------------------------------------------

    if action == "REDUCE":

        return {
            "campaign_id": campaign_id,
            "action": "REDUCE",
            "status": "EXECUTED",
            "previous_budget": current_spend,
            "new_budget": recommended_spend,
            "message": (
                f"Budget reduced from "
                f"₹{current_spend:,.2f} to "
                f"₹{recommended_spend:,.2f}"
            ),
        }

    # -----------------------------------------------------
    # PAUSE
    # -----------------------------------------------------

    if action == "PAUSE":

        return {
            "campaign_id": campaign_id,
            "action": "PAUSE",
            "status": "EXECUTED",
            "previous_budget": current_spend,
            "new_budget": 0.0,
            "message": (
                f"Campaign {campaign_id} "
                f"has been paused."
            ),
        }

    # -----------------------------------------------------
    # MAINTAIN
    # -----------------------------------------------------

    if action == "MAINTAIN":

        return {
            "campaign_id": campaign_id,
            "action": "MAINTAIN",
            "status": "NO_CHANGE",
            "previous_budget": current_spend,
            "new_budget": current_spend,
            "message": (
                f"Campaign {campaign_id} "
                f"continues with the current budget."
            ),
        }

    # -----------------------------------------------------
    # Unknown action
    # -----------------------------------------------------

    return {
        "campaign_id": campaign_id,
        "action": action,
        "status": "FAILED",
        "previous_budget": current_spend,
        "new_budget": current_spend,
        "message": "Unknown optimization action.",
    }


# =========================================================
# Execute All Decisions
# =========================================================

def execute_decisions(decisions):
    """
    Execute every decision generated by Athena.
    """

    execution_results = []

    for decision in decisions:

        result = execute_decision(
            decision
        )

        execution_results.append(
            result
        )

    return execution_results


# =========================================================
# Test Execution Layer
# =========================================================

if __name__ == "__main__":

    dataset = generate_dataset()

    decisions = generate_decisions(
        dataset
    )

    execution_results = execute_decisions(
        decisions
    )

    print("\n")
    print("=" * 70)
    print("                 ATHENA EXECUTION ENGINE")
    print("=" * 70)

    for result in execution_results:

        print("\n")

        print(
            f"Campaign: "
            f"{result['campaign_id']}"
        )

        print(
            f"Action: "
            f"{result['action']}"
        )

        print(
            f"Status: "
            f"{result['status']}"
        )

        print(
            f"Previous Budget: "
            f"₹{result['previous_budget']:,.2f}"
        )

        print(
            f"New Budget: "
            f"₹{result['new_budget']:,.2f}"
        )

        print(
            f"Message: "
            f"{result['message']}"
        )

        print("-" * 70)